### ISSUE TITLE
Can't find default configuration "arch/x86/configs/upboard_defconfig"

### ISSUE THREAD

**Issue by jasongaunt** [mopplayer/lattepanda-mainline-4.11#11]
Hi mopplayer, 

Attempting to build on a clean install of Ubuntu 16.04.3 LTS (Desktop version), I get the following error when attempting to build for my Z8300;

```make
root@lattepanda:~# cd ~/src/lattepanda-mainline-4.11/v4.12.0-rc1/

root@lattepanda:~/src/lattepanda-mainline-4.11/v4.12.0-rc1# make mrproper
  CLEAN   scripts/basic
  CLEAN   scripts/kconfig

root@lattepanda:~/src/lattepanda-mainline-4.11/v4.12.0-rc1# make upboard_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
***
*** Can't find default configuration "arch/x86/configs/upboard_defconfig"!
***
scripts/kconfig/Makefile:112: recipe for target 'upboard_defconfig' failed
make[1]: *** [upboard_defconfig] Error 1
Makefile:548: recipe for target 'upboard_defconfig' failed
make: *** [upboard_defconfig] Error 2
```

Please can you advise?

I can see a **lattepanda_64_defconfig** in the configs folder, should it be that instead?

**Comment by jasongaunt** [comment]
**Update:**

I tried **lattepanda_64_defconfig** just in case and now I get the following when running `make -j4`:

```make
scripts/sign-file.c:25:30: fatal error: openssl/opensslv.h: No such file or directory
compilation terminated.
scripts/Makefile.host:107: recipe for target 'scripts/sign-file' failed
make[1]: *** [scripts/sign-file] Error 1
Makefile:562: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: *** Waiting for unfinished jobs....
```

This is fixed by running `sudo apt install libssl-dev` and then re-running `make -j4`

Build time was roughly 3 hours.

Hoping this will help someone in future ♥
